### PR TITLE
Update aboulfad.xml

### PR DESCRIPTION
**Pull request by aboulfad**
Add Euro3 MDM setting as per post http://f80.bimmerpost.com/forums/showpost.php?p=19976613&postcount=251. This only applies to cars with fw 58.x, verified on 58.3.

### CODE REVIEW

**Comment by aboulfad** [comment]
Dave, sorry don't auto merge branches I create if I dint request you to review them. Maybe I did something wrong, but I think you just merged my recent branch used for some experimental work. I tried to revert but first time I do it.

**Comment by thisisdave** [comment]
Sorry about that @aboulfad; I thought something was off on my end. Will heed moving forward. Apologies.

**Comment by aboulfad** [comment]
No harm done, reverted the merge and all is OK! Thanks for your immediate attention though :-)

**Comment by packetpilot** [comment]
Leaving unmerged until future instructions to merge are received. Simply wanting to put an observable finger on the pulse here since this repo may become main source of truth for launcher(s).

**Pull request merged**
